home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('supervisor/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls', namespace='home')),
    path('our-team/', include('our_team.urls', namespace='our_team')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'home.views.error_404'

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='logout.html'), name='logout'),
    path('login', auth_views.LoginView.as_view(
        template_name='login.html'), name='login'),
    path('change_password', auth_views.PasswordChangeView.as_view(
        template_name='change_password.html', success_url=reverse_lazy('users:password_change_done')), name='change_password'),
    path('password_change_done', auth_views.PasswordChangeView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='users/', blank=True,
                              null=True, default=r'\users\profile-42914_640.webp')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import ReCaptchaField
from users.models import Profile


class signupform(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True
    captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']


class Userform(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class Profileform(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image',]

users/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth import login as auth_login

from .models import Profile
from .forms import Profileform, Userform, signupform

# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = signupform(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('users:profile_edit')
    else:
        form = signupform()
    cont = {'form': form}
    return render(request, 'signup.html', cont)


def profile(request):
    user_profile = Profile.objects.get(user=request.user)
    cont = {'profile': user_profile}
    return render(request, 'profile.html', cont)


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        userform = Userform(request.POST, request.FILES, instance=request.user)
        profileform = Profileform(
            request.POST, request.FILES, instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('users:profile'))
    else:
        userform = Userform(instance=request.user)
        profileform = Profileform(instance=profile)
    return render(request, 'profile_edit.html', {'profileform': profileform, 'userform': userform,'profile': profile})

users/templates/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>change password</h1>
        <div>
            <form method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-info text-white w-100" type="submit">Change</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>login</h1>
        <div>
            <form method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-info text-white w-100" type="submit">login</button>
            </form>
            <p class="w-100 text-center p-2 m-0">or</p>
            <div class="btn w-100 border mb-2 d-flex justify-content-sm-around "><img style="width: 25px;"
                    src="/media/users/google.jpg" alt=""><a class="w-100" href="{% provider_login_url 'google' %}">login
                    Using
                    Google</a>
            </div>
            <div class="card-footer text-muted text-center">don't have an account <a
                    href="{% url 'users:signup' %}">create one</a></div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/logout.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>Logged out</h1>
        <div>
            <a href="{% url 'users:login' %}">Log in again</a>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/password_change_done.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>password changed successfully</h1>
        <div>
            <div class="alert alert-success" role="alert">
                your password has been changed
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>Profile</h1>
        <div>
            <div>
                <div class="single_candidates text-center">
                    <div class="thumb">
                        <img src="{{profile.image.url}} " class="rounded-circle" style="width: 20%;" alt="">
                    </div>
                </div>
            </div>
            <div class="d-flex align-items-center p-4  flex-column">
                <ul>
                    <li>user : <span>{{profile.user}}</span></li>
                    <li>frist name : <span> {{profile.user.first_name}}</span></li>
                    <li>last name : <span>{{profile.user.last_name}}</span></li>
                    <li>E-mail : <span>{{profile.user.email}}</span></li>
                </ul>
                <a href="{% url 'users:profile_edit' %}" class=" text-center boxed-btn3 w-100">Edit</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/profile_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>Profile</h1>
        <div>
            <div>
                <div class="single_candidates text-center">
                    <div class="thumb">
                        <img src="{{profile.image.url}} " class="rounded-circle" style="width: 20%;" alt="">
                    </div>
                </div>
            </div>
            <h4>edit profile</h4>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form userform %}
                <br>
                {% bootstrap_form profileform %}
                <br>
                <button class="btn btn-info text-white w-100" type="submit">Change Now</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container col-lg-6 d-flex align-items-center rounded bg-light flex-column p-4">
        <h1>SignUp</h1>
        <div>
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% for error in form.captcha.errors %}
                <p class="text-danger">{{error}}</p>
                {% endfor %}
                <div class="col-12">
                    <button class="btn btn-info text-white w-100" type="submit">Signup</button>
                </div>
                <p class="w-100 text-center p-2 m-0">or</p>
                <div class="btn w-100 border mb-2 d-flex justify-content-sm-around "><img style="width: 25px;"
                        src="/media/users/google.jpg" alt=""><a class="w-100"
                        href="{% provider_login_url 'google' %}?next={% url 'users:profile_edit' %}">signup Using
                        Google</a>
                </div>
            </form>
            <div class="card-footer text-muted text-center">already have an account <a
                    href="{% url 'users:login' %}">login</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}