about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.about, name='about'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.courses, name='courses'),
    path('list', views.courses_list, name='courses_list'),
    path('<str:slug>', views.course_desc, name='course_desc'),
    path('<str:slug>/enroll', views.courses_enroll, name='courses_enroll'),
    path('courses/enrolled', views.enroll_done, name='enroll_done'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

our_team/urls.py
from django.urls import path
from . import views

app_name = 'our_team'
urlpatterns = [
    path('', views.our_team, name='our_team'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('supervisor/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls', namespace='home')),
    path('our-team/', include('our_team.urls', namespace='our_team')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'home.views.error_404'

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from our_team.models import Team
# Create your views here.


def about(request):
    team = Team.objects.all()
    cont = {'team': team}
    return render(request, 'about.html', cont)

about/templates/about.html
{% extends "base.html" %}{% load static %}
{% block content %}
<!-- Header Start -->
<div class="container-fluid bg-primary py-5 mb-5 page-header">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <h1 class="display-3 text-white animated slideInDown">About Us</h1>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->


<!-- Service Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4">
            <a href="{% url 'our_team:our_team' %}" class="col-lg-3 col-sm-6 wow fadeInUp text-dark"
                data-wow-delay="0.1s">
                <div class="service-item text-center pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-graduation-cap text-primary mb-4"></i>
                        <h5 class="mb-3">Skilled Instructors</h5>
                        <p>With blended learning on the rise alongside mobile apps that distract rather than develop
                            employees, it’s important not
                            to underestimate the value of a great trainer or instructor. Below are seven skills highly
                            effective instructors and
                            trainers must have in the modern-day workplace.</p>
                    </div>
                </div>
            </a>
            <a href="{% url 'courses:courses' %}" class="col-lg-3 col-sm-6 wow fadeInUp text-dark"
                data-wow-delay="0.3s">
                <div class="service-item text-center pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-globe text-primary mb-4"></i>
                        <h5 class="mb-3">Online Classes</h5>
                        <p>we have been actively involved in conducting online classes, utilizing various platforms and
                            technologies to deliver engaging and interactive learning experiences. Through our teaching
                            career, we have developed a
                            deep understanding of effective online instructional strategies.</p>
                    </div>
                </div>
            </a>
            <a href="" class="col-lg-3 col-sm-6 wow fadeInUp text-dark" data-wow-delay="0.5s">
                <div class="service-item text-center pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-home text-primary mb-4"></i>
                        <h5 class="mb-3">Home Projects</h5>
                        <p>I am writing to express my interest in the "Home Projects" opportunity at Company. With my
                            passion
                            for home improvement and project management skills, I believe I would be an excellent fit
                            for this role.</p>
                    </div>
                </div>
            </a>
            <a href=" " class="col-lg-3 col-sm-6 wow fadeInUp text-dark" data-wow-delay="0.7s">
                <div class="service-item text-center pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-book-open text-primary mb-4"></i>
                        <h5 class="mb-3">Book Library</h5>
                        <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- Service End -->

<!-- About Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s" style="min-height: 400px;">
                <div class="position-relative h-100">
                    <img class="img-fluid position-absolute w-100 h-100" src="{% static 'img/about.jpg' %}" alt=""
                        style="object-fit: cover;">
                </div>
            </div>
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.3s">
                <h6 class="section-title bg-white text-start text-primary pe-3">About Us</h6>
                <h1 class="mb-4">Welcome to eLEARNING</h1>
                <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et
                    eos. Clita erat ipsum et lorem et sit.</p>
                <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et
                    eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                <div class="row gy-2 gx-4 mb-4">
                    <div class="col-sm-6">
                        <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Skilled Instructors</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Online Classes</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>International Certificate</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Skilled Instructors</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Online Classes</p>
                    </div>
                    <div class="col-sm-6">
                        <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>International Certificate</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->


<!-- Team Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Instructors</h6>
            <h1 class="mb-5">Expert Instructors</h1>
        </div>
        <div class="row g-4">

            {% for team in team %}

            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="team-item bg-light">
                    <div class="overflow-hidden">
                        <img class="img-fluid h-100 w-100" src="{{team.image.url}}" alt="">
                    </div>
                    <div class="position-relative d-flex justify-content-center" style="margin-top: -23px;">
                        <div class="bg-light d-flex justify-content-center pt-2 px-1">
                            <a class="btn btn-sm-square btn-primary mx-1" href="{{team.facebook}}"><i
                                    class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-sm-square btn-primary mx-1" href="{{team.twitter}}"><i
                                    class="fab fa-twitter"></i></a>
                            <a class="btn btn-sm-square btn-primary mx-1" href="{{team.instagram}}"><i
                                    class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                    <div class="text-center p-4">
                        <h5 class="mb-0">{{team.name}}</h5>
                        <small>{{team.position}}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>


    </div>
</div>
</div>
<!-- Team End -->

{% endblock content %}