courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.courses, name='courses'),
    path('list', views.courses_list, name='courses_list'),
    path('<str:slug>', views.course_desc, name='course_desc'),
    path('<str:slug>/enroll', views.courses_enroll, name='courses_enroll'),
    path('courses/enrolled', views.enroll_done, name='enroll_done'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('supervisor/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls', namespace='home')),
    path('our-team/', include('our_team.urls', namespace='our_team')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'home.views.error_404'

courses/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="category/")

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    period = models.DecimalField(max_digits=5, decimal_places=2)
    instructor = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    image = models.ImageField(upload_to='courses/')
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name='comments', null=True)
    comment = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.course.name}"

courses/forms.py
from django import forms


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)

courses/views.py
from django.conf import settings
from django.core.mail import send_mail
from .filters import CourseFilter
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render,get_object_or_404
from .models import Course, Category, Comment
from .forms import CommentForm
# Create your views here.


def courses(request):
    course = Course.objects.all()
    category = list(Category.objects.all())
    student = Comment.objects.order_by('?')[:6]
    for c in category:
        c.coursecount = len(course.filter(category=c))
    cont = {'course': course, 'category': category, 'student': student}
    return render(request, 'courses.html', cont)


def courses_list(request):
    courses = Course.objects.all()
    filter = CourseFilter(request.GET, queryset=courses)
    cont = {
        'courses': filter.qs,
        'form': filter.form,
    }
    return render(request, 'courses_list.html', cont)


@login_required
def course_desc(request, slug):
    course = get_object_or_404(Course, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data['comment']
            Comment.objects.create(
                user=request.user, course=course, comment=comment_text)
            return redirect(request.path)
    else:
        form = CommentForm()

    student = Comment.objects.all().filter(course_id=course.pk)

    cont = {'form': form, 'course': course, 'student': student}
    return render(request, 'desc.html', cont)


@login_required
def courses_enroll(request, slug):
    course = Course.objects.get(slug=slug)
    if request.method == 'POST':
        name = request.user
        email = request.user.email
        subject = course
        send_mail(
            subject,
            f'\"{name}\" Want to enroll in {course} \nSender Email is : {email}',
            email,
            [settings.EMAIL_HOST_USER],
        )
        return redirect('courses:enroll_done')
    return render(request, 'enroll.html', {'course': course})


def enroll_done(request):
    return render(request, 'enroll_done.html')

courses/templates/courses.html
{% extends "base.html" %}{% block content %}
<!-- Header Start -->
<div class="container-fluid bg-primary py-5 mb-5 page-header">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <h1 class="display-3 text-white animated slideInDown">Courses</h1>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->


<!-- Categories Start -->
<div class="container-xxl py-5 category">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Categories</h6>
            <h1 class="mb-5">Courses Categories</h1>
        </div>
        {% if category|length > 0 %}
        <div class="row g-3">
            <div class="col-lg-7 col-md-6">
                <div class="row g-3">
                    <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                        <a class="position-relative d-block overflow-hidden"
                            href="{% url 'courses:courses_list'%}?category={{category.0.id}}">
                            <img class="img-fluid" src="{{category.0.image.url}}" alt="">
                            <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3"
                                style="margin: 1px;">
                                <h5 class="m-0">{{category.0.name}}</h5>
                                <small class="text-primary">{{category.0.coursecount}} Courses</small>
                            </div>
                        </a>
                    </div>
                    {% if category|length > 1 %}
                    <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.3s">
                        <a class="position-relative d-block overflow-hidden"
                            href="{% url 'courses:courses_list'%}?category={{category.1.id}}">
                            <img class="img-fluid" src="{{category.1.image.url}}" alt="">
                            <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3"
                                style="margin: 1px;">
                                <h5 class="m-0">{{category.1.name}}</h5>
                                <small class="text-primary">{{category.1.coursecount}} Courses</small>
                            </div>
                        </a>
                    </div>
                    {% endif %}
                    {% if category|length > 2 %}
                    <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.5s">
                        <a class="position-relative d-block overflow-hidden"
                            href="{% url 'courses:courses_list'%}?category={{category.2.id}}">
                            <img class="img-fluid" src="{{category.2.image.url}}" alt="">
                            <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3"
                                style="margin: 1px;">
                                <h5 class="m-0">{{category.2.name}}</h5>
                                <small class="text-primary">{{category.2.coursecount}} Courses</small>
                            </div>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% if category|length > 3 %}
            <div class="col-lg-5 col-md-6 wow zoomIn" data-wow-delay="0.7s" style="min-height: 350px;">
                <a class="position-relative d-block h-100 overflow-hidden"
                    href="{% url 'courses:courses_list'%}?category={{category.3.id}}">
                    <img class="img-fluid position-absolute w-100 h-100" src="{{category.3.image.url}}" alt=""
                        style="object-fit: cover;">
                    <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin:  1px;">
                        <h5 class="m-0">{{category.3.name}}</h5>
                        <small class="text-primary">{{category.3.coursecount}} Courses</small>
                    </div>
                </a>
            </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
</div>
<!-- Categories End -->


<!-- Courses Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>
            <h1 class="mb-5">Popular Courses</h1>
        </div>
        <div class="row g-4 justify-content-center">
            {% for course in course|slice:":6" %}
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="course-item bg-light">
                    <div class="position-relative overflow-hidden" style="max-height: 165px;">
                        <img class="img-fluid w-100 h-100" src="{{course.image.url}}" alt="">
                        <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                            <a href="{% url 'courses:course_desc' course.slug%}"
                                class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end"
                                style="border-radius: 30px 0 0 30px;">Read More</a>
                            <a href="{% url 'courses:courses_enroll' course.slug%}"
                                class="flex-shrink-0 btn btn-sm btn-primary px-3"
                                style="border-radius: 0 30px 30px 0;">Join Now</a>
                        </div>
                    </div>
                    <div class="text-center p-4 pb-0">
                        <h3 class="mb-0">${{course.price}}</h3>
                        <h5 class="mb-4">{{course}}</h5>
                    </div>
                    <div class="d-flex border-top">
                        <small class="flex-fill text-center border-end py-2"><i
                                class="fa fa-user-tie text-primary me-2"></i>{{course.instructor}}</small>
                        <small class="flex-fill text-center border-end py-2"><i
                                class="fa fa-clock text-primary me-2"></i>{{course.period}}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="text-center p-4">
        <a href="{% url 'courses:courses_list' %}" class="w-50 flex-shrink-0 btn btn-sm btn-primary px-3"
            style="border-radius: 30px ;">Browse More
            courses</a>
    </div>
</div>
<!-- Courses End -->


<!-- Testimonial Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="text-center">
            <h6 class="section-title bg-white text-center text-primary px-3">Testimonial</h6>
            <h1 class="mb-5">Our Students Say!</h1>
        </div>
        <div class="owl-carousel testimonial-carousel position-relative h-100">
            {% for student in student %}
            <div class="testimonial-item text-center ">
                <img class="border rounded-circle p-2 mx-auto mb-3 " src="{{student.user.profile.image.url}}"
                    style="width: 80px; height: 80px;">
                <h5 class="mb-0">{{student.user.first_name}}</h5>
                <p>{{student.course|truncatechars:50}}</p>
                <div class="testimonial-text bg-light text-center p-4" style="word-wrap: break-word;">
                    <p class="mb-0">{{student.comment}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Testimonial End -->
{% endblock content %}

courses/templates/courses_list.html
{% extends "base.html" %}{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>
            <h1 class="mb-5">Popular Courses</h1>
        </div>
        <div class="d-flex">
            <form class=" bg-light  w-50" method="get">
                {% bootstrap_form form %}
                <button class="w-100  btn btn-sm btn-primary my-3" type="submit">Apply Filter</button>
            </form>
            <div>
                <div class="row g-4 justify-content-center">
                    {% for course in courses %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp w-auto" data-wow-delay="0.1s">
                        <div class="course-item bg-light" style=" width: 300px; ">
                            <div class="position-relative overflow-hidden w-100">
                                <img class="img-fluid w-100 " src="{{course.image.url}}" alt=""
                                    style=" max-height: 165px; ">
                                <div
                                    class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                    <a href="{% url 'courses:course_desc' course.slug%}"
                                        class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end"
                                        style="border-radius: 30px 0 0 30px;">Read More</a>
                                    <a href="{% url 'courses:courses_enroll' course.slug%}"
                                        class="flex-shrink-0 btn btn-sm btn-primary px-3"
                                        style="border-radius: 0 30px 30px 0;">Join Now</a>
                                </div>
                            </div>
                            <div class="text-center p-4 pb-0">
                                <h3 class="mb-0">${{course.price}}</h3>
                                <h5 class="mb-4">{{course}}</h5>
                            </div>
                            <div class="d-flex border-top">
                                <small class="flex-fill text-center border-end py-2"><i
                                        class="fa fa-user-tie text-primary me-2"></i>{{course.instructor}}</small>
                                <small class="flex-fill text-center border-end py-2"><i
                                        class="fa fa-clock text-primary me-2"></i>{{course.period}}</small>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h1 class="text-center">No courses found.</h1>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

courses/templates/desc.html
{% extends "base.html" %}{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5 d-flex justify-content-center">
    <div class=" d-flex align-items-center rounded bg-light flex-column p-4 w-50">
        <div class="col-lg-4 col-md-6 wow fadeInUp w-100" data-wow-delay="0.1s">
            <div class="course-item bg-light">
                <div class="position-relative overflow-hidden">
                    <img class="img-fluid w-100 h-100" src="{{course.image.url}}" alt="">
                </div>
                <div class="text-center p-4 pb-0">
                    <h3 class="mb-0">${{course.price}}</h3>
                    <h5 class="mb-4">{{course}}</h5>
                    <p>{{course.description}}</p>
                </div>
                <div class="d-flex border-top">
                    <small class="flex-fill text-center border-end py-2"><i
                            class="fa fa-user-tie text-primary me-2"></i>{{course.instructor}}</small>
                    <small class="flex-fill text-center border-end py-2"><i
                            class="fa fa-clock text-primary me-2"></i>{{course.period}}</small>
                </div>
                <a href="{% url 'courses:courses_enroll' course.slug%}"
                    class="w-100 flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 30px ;">Join
                    Now</a>
                <form method="post" class="pt-4">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="hidden" name="course_id" value="{{ course.id }}">
                    <button class="btn btn-info text-white w-100" type="submit">Comment</button>

                </form>
                <div class="container p-0 overflow-auto " style="height: 500px;">
                    {% for student in student %}
                    <div class="card mt-3">
                        <div class="card-body">
                            <img class="border rounded-circle  " src="{{student.user.profile.image.url}}"
                                style="width: 60px; height: 60px;">
                            <div class="" style="padding-left: 80px;margin-top: -60px;">
                                <h5 class="card-title p-0 m-0">{{student.user.first_name}}</h5>
                                <small class="text-black-50">{{student.created_at}} </small>
                                <p class="card-text">{{student.comment}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

courses/templates/enroll.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5 d-flex justify-content-center">
    <div class=" d-flex align-items-center rounded bg-light flex-column p-4 w-50">
        <div class="col-lg-4 col-md-6 wow fadeInUp w-100" data-wow-delay="0.1s">
            <div class="course-item bg-light">
                <div class="position-relative overflow-hidden">
                    <img class="img-fluid w-100 h-100" src="{{course.image.url}}" alt="">
                </div>
                <div class="text-center p-4 pb-0">
                    <h3 class="mb-0">${{course.price}}</h3>
                    <h5 class="mb-4">{{course}}</h5>
                    <p>{{course.description}}</p>
                </div>
                <div class="d-flex border-top">
                    <small class="flex-fill text-center border-end py-2"><i
                            class="fa fa-user-tie text-primary me-2"></i>{{course.instructor}}</small>
                    <small class="flex-fill text-center border-end py-2"><i
                            class="fa fa-clock text-primary me-2"></i>{{course.period}}</small>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Enroll</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

courses/templates/enroll_done.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container-xxl py-5 d-flex justify-content-center">
    <div class=" d-flex align-items-center rounded bg-light flex-column p-4 w-50">
        <h1>enrollment done</h1>
        <h3>you will recieve an e-mail in 24 hours</h3>
    </div>
</div>
{% endblock content %}