about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.about, name='about'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.courses, name='courses'),
    path('list', views.courses_list, name='courses_list'),
    path('<str:slug>', views.course_desc, name='course_desc'),
    path('<str:slug>/enroll', views.courses_enroll, name='courses_enroll'),
    path('courses/enrolled', views.enroll_done, name='enroll_done'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('supervisor/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls', namespace='home')),
    path('our-team/', include('our_team.urls', namespace='our_team')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'home.views.error_404'

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='logout.html'), name='logout'),
    path('login', auth_views.LoginView.as_view(
        template_name='login.html'), name='login'),
    path('change_password', auth_views.PasswordChangeView.as_view(
        template_name='change_password.html', success_url=reverse_lazy('users:password_change_done')), name='change_password'),
    path('password_change_done', auth_views.PasswordChangeView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>DaDa - ELEARNING</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="" />
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&amp;family=Nunito:wght@600;700;800&amp;display=swap"
        rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
</head>

<body class="text-capitalize">
    <!-- Spinner Start -->
    <div id="spinner"
        class="bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0" style="top: -100px">
        <a href="{% url 'home:home' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary">
                <i class="fa fa-book me-3"></i>DaDa
            </h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url 'home:home' %}" class="nav-item nav-link active">Home</a>
                <a href="{% url 'about:about' %}" class="nav-item nav-link">About</a>
                <a href="{% url 'courses:courses' %}" class="nav-item nav-link">Courses</a>
                <a href="{% url 'our_team:our_team' %}" class="nav-item nav-link">Our Team</a>
                <a href="{% url 'contact:contact' %}" class="nav-item nav-link">Contact</a>
                {% if request.user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'users:profile' %}">My account</a>
                            <a class="dropdown-item" href="{% url 'users:change_password' %}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a>
                        </div>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
        <a href="{% url 'users:signup' %}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i
                class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </nav>
    <!-- Navbar End -->
    {% block content %}

    {% endblock content %}
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s"
        style="visibility: hidden; animation-delay: 0.1s; animation-name: none">
        <div class="container py-5">
            <div class="row g-5 justify-content-center">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Quick Link</h4>
                    <a class="btn btn-link" href="{% url 'about:about' %}">About Us</a>
                    <a class="btn btn-link" href="{% url 'contact:contact' %}">Contact Us</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2">
                        <i class="fa fa-map-marker-alt me-3"></i>Egypt-Cairo-Zayton

                    </p>
                    <p class="mb-2">
                        <i class="fa fa-phone-alt me-3"></i>01002797591
                    </p>
                    <p class="mb-2">
                        <i class="fa fa-envelope me-3"></i>Doux0111@Gmail.Com
                    </p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/Doux100/"><i
                                class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/Doux100/"><i
                                class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/Doux100/"><i
                                class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/Doux100/"><i
                                class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        © <a class="border-bottom" href="{% url 'home:home' %}">DaDa</a>, All Right
                        Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By
                        <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top" style="display: none"><i
            class="	fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/notfound.html
{% extends "base.html" %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4">
            <div data-wow-delay="0.1s">
                <div class="bg-light text-center pt-3">
                    <div class="p-4">
                        <i class="fa fa-3x fa-window-close text-primary mb-4"></i>
                        <h5 class="mb-3">We can’t find this page</h5>
                        <p>It looks like this page doesn't exist or isn’t available right now.
                            Please Check the URL or go to <a href="{% url 'home:home' %}">home</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}